# application-qa.yml
spring:
  messages:
    basename:  "This is a message for the QA environment."

### mongoDB
### Database configuration
  data:
    mongodb:
      uri : mongodb://localhost:27017/
      database : mongoDB-QA