# application-dev.yml
spring:
  messages:
    basename: "This is a message for the development environment"
  ### mongoDB
  ### Database configuration
#  data:
#    mongodb:
#      uri : mongodb://localhost:27017/
#      database : mongoDB-dev
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: root


